//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderValues
    {
        public int orderid { get; set; }
        public Nullable<int> custid { get; set; }
        public int empid { get; set; }
        public int shipperid { get; set; }
        public System.DateTime orderdate { get; set; }
        public Nullable<decimal> val { get; set; }
    }
}
